feat: auth/credential support
yomorun/cli pull request #21
Opened 2022-04-15 12:12 UTC by venjiang

2022-04-15 14:12 UTC, fanweixiao requested changes

2022-04-15 14:12 UTC, fanweixiao commented on example/go.mod
> +replace github.com/yomorun/yomo => ../../yomo
should remove this line

2022-04-15 14:12 UTC, fanweixiao commented on example/source/main.go
> +		yomo.WithCredential("token:1234"),
Suggest read `YOMO_TOKEN` in `NewSource` automatically.

2022-04-15 14:12 UTC, fanweixiao commented on go.mod
> +replace github.com/yomorun/yomo => ../yomo
should remove this line.

2022-04-15 14:12 UTC, fanweixiao commented on serverless/golang/serverless.go
> +		log.InfoStatusEvent(os.Stdout, "Credential=%s", credential)
should remove this log for security reason.

2022-04-15 14:12 UTC, fanweixiao commented on serverless/js/serverless.go
> +		log.InfoStatusEvent(os.Stdout, "Credential=%s", credential)
should remove this log for security reason.

2022-04-15 14:12 UTC, fanweixiao commented on cmd/serve.go
> +			idx := strings.Index(auth, ":")
Will a `AuthorizationFunc` is better?

2022-04-15 14:36 UTC, venjiang commented on example/go.mod
> +replace github.com/yomorun/yomo => ../../yomo
Yeah, I known，It need review after `YoMo` PR merged.

2022-04-15 14:37 UTC, venjiang commented on serverless/golang/serverless.go
> +		log.InfoStatusEvent(os.Stdout, "Credential=%s", credential)
Get

2022-04-15 14:43 UTC, venjiang commented on example/source/main.go
> +		yomo.WithCredential("token:1234"),
“token:1234” is credential payload,It’s can be anything. eg: “jwt:ugghjytffhj”

2022-04-22 02:41 UTC, wujunzhuo approved these changes

2022-04-22 03:48 UTC, xiaojian-hong approved these changes

2022-04-22 12:52 UTC, fanweixiao approved these changes

2022-04-22 12:55 UTC, merged